### ISSUE TITLE
[dockerv2] Remove rec.Root in favor of rec.Website?

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#204]
**What happened**:
Do we really need rec.Root for dockerv2?

**What you expected to happen**:
Use rec.Website as the main fallback within dockerv2.

**Anything else we need to know?**:
Full fallback flow:
rec.Website > path.rec.To > *www* defaulting on instance > *redirect* on instance

**Comment by stp-ip** [comment]
Taking into consideration the usage without path it makes sense to have this separate.
rec.Website + rec.Root I think. Would still love additional thoughts, but I think this could be closed.

**Comment by erbesharat** [comment]
I think keeping both of them is better. Since we use `rec.Root` in path too using it with docker+path makes sense too.

Sidenote: I found something when I was looking for `rec.Root` usages. I think we should use fallback function in here.
https://github.com/txtdirect/txtdirect/blob/2c488fc5b20b86cca20daacd78b490478c37f6c1/txtdirect.go#L220-L228

**Comment by stp-ip** [comment]
Yes fallback seems like a good solution here. Also happy to keep rec.Root.

**Comment by stp-ip** [comment]
Question is, when would be actually trigger rec.Root in dockerv2?

It's either rec.Website aka the fallback or has a path due to dockerv2.
So even so rec.Root might be kept it wouldn't have any usage in dockerv2 right?

As no docker registry request will use / the root path and anything that isn't a docker registry request will be using rec.Website by default. I think that was the main idea, behind just not including it within the spec. Basically saying rec.Root is non existent as it wouldn't be used.
