### ISSUE TITLE
[gometa + path] Subpackages usage ideas

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#222]
**Anything else we need to know?**:
The idea is to split a go-gettable path from the actual code usage one.
1. `go get go.resumic.org/resumic` -> resumic help working
2. `import "go.resumic.org/schema/jsonschema` -> import subpackages via vanity url

DNS
```
go                   86400 IN CNAME   gometa.txtd.io.
_redirect.go            30 IN TXT     "v=txtv0;to=https://about.okkur.org/#resumic;type=path"
_redirect.resumic.go    30 IN TXT     "v=txtv0;to=https://github.com/resumic/schema;type=gometa"
_redirect._.schema.go   30 IN TXT     "v=txtv0;to=https://github.com/resumic{path};type=gometa"
```

1. works as expected
2. doesn't work as it's not considered an importable package

Does it have to do with our base path that doesn't include the path? I might have been wrong with #201. Rereading the docs on go-import it should be the exact match than is requested. This would include the path. 

Will test, if it works without the "fix" for #201 such as this config:
```
_redirect._.schema.go.resumic.org. 30 IN TXT     "v=txtv0;to=https://github.com/resumic{path};type=gometa"
```

This should give a go-import record such as:
```
<meta name="go-import" content="go.resumic.org/schema/jsonschema git https://github.com/resumic/schema/jsonschema">
```

Happy to hear additional thoughts on this.

**Comment by erbesharat** [comment]
I believe the changes that we made to gometa caused the problem.

Logs with #201 changes:
```
127.0.0.1 - [2019-03-30T13:28:18Z] "GET /resumic?go-get=1 HTTP/1.1" 200 306 4ms
WARN: txtv0 is not suitable for production
[txtdirect]: pkg.example.test/ > https://about.okkur.org/#resumic
127.0.0.1 - [2019-03-30T13:28:18Z] "GET /?go-get=1 HTTP/1.1" 302 55 468µs
```
On the third line you can see that it doesn't have access to the path so it uses `_redirect.pkg` instead of the gometa record.

Tested it without the changes on gometa and it fetched the package successfuly and I did import and use it using `import "pkg.example.test/resumic/schema"` without any problem.

**Comment by stp-ip** [comment]
Yes I thought I opened an issue relating to reverting the #201 change. But seems I only mentioned it in chat. My fault sorry. Happy for us to revert that change.
Also we should add tests for the specific cases mentioned here.
Let me dig up the specific issue, why I felt it's broken.

**Comment by stp-ip** [comment]
Ah yeah the catch-all use case with gometa doesn't like the .Path as this won't work on a catch-all.
That was the primary reason #201 was done.
I thought that would work due to Sally from Uber also not using Path. Is this due to different usage?
Happy to look into it, if you can't find anything more specific. Let me know.

**Comment by erbesharat** [comment]
Currently, with reverting #201 changes, we have `gometa` that works fine and also using `path` type with `gometa` is supported.

example records that work fine:
**Gometa**: 
```
pkg                   IN A 127.0.0.1
_redirect.pkg            30 IN TXT     "v=txtv0;to=https://github.com/resumic/schema;type=gometa"
```
**Gometa+Path**:
```
pkg                   IN A 127.0.0.1
_redirect.pkg            30 IN TXT     "v=txtv0;to=https://about.okkur.org/#resumic;type=path"
_redirect.resumic.pkg   30 IN TXT    "v=txtv0;to=https://github.com/resumic/schema;type=gometa"
```
Usage: `go get pkg.example.test/resumic`

But pointing a record to a subpackage like `github.com/resumic/schema/schema` is not possible right now.
It's because `go get` doesn't identify the base package from a go-import tag. (It works fine directly, but doesn't work with go-import)
A solution that fixes this problem is identifying the base package from `rec.To` but to do that we have to identify the vcs and hosting sites which would only be possible by adding lots of complex logic to our code.

`go get` already does that *identifying* step before downloading the package. It uses a function called `RepoRootForImportPath` [[1]] from `internal/get/vcs.go` package. Which uses a list of hosting sites located at [[2]] to identify the vcs used in the package and then finds the root/base packages.

To support subpackages inside gometa we have to add all of those additional steps to our code which adds lots of complexity.

There is also another way to separate the base package from subpackages, which is using the base package's URI inside the subpackage's record.
Example:
```
pkg                   IN A 127.0.0.2
_redirect.pkg            30 IN TXT     "v=txtv0;to=https://about.okkur.org/#resumic;type=path"
_redirect.resumic.pkg   30 IN TXT    "v=txtv0;to=https://github.com/resumic/schema;type=gometa"
_redirect.schema.pkg   30 IN TXT    "v=txtv0;to=https://github.com/resumic/schema;type=gometa"
```
I think it doesn't make that much of a difference because even using the subpackage's url directly with `go get`, aka without gometa, downloads the whole package, instead of just the subpackage.

---

[1]: https://github.com/golang/go/blob/df557fe3ea94ff8888abd6a6ab4cc5d5351d77a6/src/cmd/go/internal/get/vcs.go#L653

[2]: https://github.com/golang/go/blob/df557fe3ea94ff8888abd6a6ab4cc5d5351d77a6/src/cmd/go/internal/get/vcs.go#L980

**Comment by stp-ip** [comment]
Closing as nothing much to do here. Thanks for the thorough investigation.
