### ISSUE TITLE
Discuss/allow chaining of path based records

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#75]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently a redirect to another path based record will trigger the fallback code and not use the last path record in the chain.

**What you expected to happen**:
Possibility to allow chaining of path based records.

**Anything else we need to know?**:
Related discussions: https://github.com/txtdirect/txtdirect/pull/66

**Comment by erbesharat** [comment]
Since we now have access to previous records via request context, we can trace back a path record to its parent when they're chained.

Before storing records in the context, we didn't have access to the parent records, so debugging and logging errors was much more unclear. But now we have access to the request flow through the path records, so we can easily log the redirects between path records and debugging would be clear and easy enough.

Also, we already have a good fallback flow, which fallbacks to the previous path record when something goes wrong with the final record. So even our error handling is already good enough for supporting path chaining.

Supporting path chaining gives us some features like having multiple subdomains with their own wildcards bound together using path chaining.
Also, we can add a new feature to use the parent record's values like `re=`, `from=`, and etc inside the children record. Like this example:
```
_redirect.path.example.test.      IN TXT "v=txtv0;re=\d+;to=https://result.example.test/to;type=path;code=302"
_redirect.releases.path.example.test.      IN TXT "v=txtv0;re=parent;to=https://github.com/txtdirect/txtdirect/relases;type=path;code=302"
```

We can also add a few new metrics to track children stats in path chaining.
